service: ec2-instances-switcher

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:StartInstances"
        - "ec2:StopInstances"
      Resource: "*"
  environment:
    tag_name: ec2-instances-switcher-isenabled
    public_holiday_api: ${opt:public_holiday_api}

package:
  exclude:
    - README.md
    - template.yaml

layers:
  ec2InstancesSwitcher:
    path: layer

functions:
  start:
    handler: instances/start.handler
    layers:
      - {Ref: Ec2InstancesSwitcherLambdaLayer}
    events:
      - schedule: cron(0 23 ? * SUN-THU *)
  stop:
    handler: instances/stop.handler
    layers:
      - {Ref: Ec2InstancesSwitcherLambdaLayer}
    events:
      - schedule: cron(0 12 ? * MON-FRI *)
